### ISSUE TITLE
Incompatibility with Illuminate\Database\Eloquent\Model::delete()

### ISSUE THREAD

**Issue by cdiehl83** [appstract/laravel-options#16]
After installing this package and migrating I get the following error whenever using the option global helper in a route.

"Declaration of Appstract\Options\Option::delete($key) should be compatible with Illuminate\Database\Eloquent\Model::delete()"

After commenting out the delete($key) method everything seems to work just fine

**Comment by teuunn** [comment]
#14 related

**Comment by gizburdt** [comment]
Fixed in v2.0.0 (tagged a couple of minutes ago 👍)
