### ISSUE TITLE
Enable travis checks for PRs to pass

### ISSUE THREAD

**Issue by MarkVaughn** [appstract/laravel-options#21]
I have a few suggestions for the project.
First I think it would benefit if the PRs could have the travis check block merging.

They are enabled on a per branch basis by checking the 
https://github.com/appstract/laravel-options/settings/branches
![image](https://user-images.githubusercontent.com/39970/53417998-884b2280-39b5-11e9-8c37-9a77d841a987.png)

Further recommend removing  `- COMPOSER_FLAGS="--prefer-lowest"` from the travis.yml file.

And finally in the https://github.com/appstract/laravel-options/settings setting the merge button to squash merge
![image](https://user-images.githubusercontent.com/39970/53418102-c8120a00-39b5-11e9-896b-8b2629e0527d.png)
Squash merging PRs reduces the amount of nit/fix commits to one

**Comment by gizburdt** [comment]
Hi,

Thanks for the feedback :)

I can't select a status check (yet?) on the master branch.

Allow squash merging is enabled by default.

**Comment by gizburdt** [comment]
I merged the Travis branch with master, so now I can enable the status checks.

**Comment by MarkVaughn** [comment]
Awesome, thanks for the quick response!
