### ISSUE TITLE
A feature question

### ISSUE THREAD

**Issue by JimChenWYU** [appstract/laravel-options#24]
Hi,
Now, we can only get options from database, but sometime i do not change them frequently, so in a short time, they seem like constant.

Yep, i want to ask, in the future the project will be added a feature about to cache options from database or not.

**Comment by akhzarjaved** [comment]
> 
> 
> Hi,
> Now, we can only get options from database, but sometime i do not change them frequently, so in a short time, they seem like constant.
> 
> Yep, i want to ask, in the future the project will be added a feature about to cache options from database or not.

Or maybe a function to get all options of the system so we can apply laravel cache upon that.

**Comment by gizburdt** [comment]
Caching is a nice idea, maybe you can create a PR for this? :)

**Comment by atiqsamtia** [comment]
I'm working on the cache, will send a PR soon.
