### ISSUE TITLE
User-specific options

### ISSUE THREAD

**Issue by bendix-dev** [appstract/laravel-options#27]
It would be cool if you would be able to store key/value pairs by user so just add the user id to the table and make the option-function only getting the value by key and user.

**Comment by teuunn** [comment]
Hi @TaskPlays,

I like the idea, but it's not really generic for every application. Bit the same situation as discussed in #25.

**Comment by gizburdt** [comment]
Hi @TaskPlays,

Like Teun said, it's not generic enough to be implemented in this package. Also, this package is for global key value storage. If you want to attach data to a user (or model), have a look at our laravel-meta package :)
