### ISSUE TITLE
Change Type Key In DB

### ISSUE THREAD

**Issue by hadikhezrpour** [appstract/laravel-options#46]
How Can I Change Type Key From Varchar To Text?

**Comment by gizburdt** [comment]
You can publish the migration and change the type of the column :)

**Comment by hadikhezrpour** [comment]
How?

**Comment by gizburdt** [comment]
With `php artisan vendor:publish --provider="Appstract\Options\OptionsServic` you can publish the migrations. The migration will be published to database/migrations. You can then change this line: https://github.com/appstract/laravel-options/blob/master/database/migrations/2017_03_03_100000_create_options_table.php#L18
