### ISSUE TITLE
Getting Error in Laravel 8: BadMethodCallException Call to undefined method Appstract\Options\Option::option_all()

### ISSUE THREAD

**Issue by m-sajjad01** [appstract/laravel-options#54]
After installing this package and migrating I got the following error. I made this below function in "vendor/appstract/laravel-options/src/helpers.php"

if (! function_exists('option_all')) {
    /**
     * Get all options in key => value pair
     *
     * @return array
     */
    function option_all()
    {
        return app('option')->option_all();
    }
}
but I am getting this error "BadMethodCallException Call to undefined method Appstract\Options\Option::option_all()" and unable to resolve.  It's urgent Please advise.

**Comment by gizburdt** [comment]
Which version are you using? option_all doesn't exist anymore.

Did you run `composer dump:autoload` after you migrated to the new version?

**Comment by m-sajjad01** [comment]
Thank you for your reply @gizburdt  
I have installed from here --> https://github.com/appstract/laravel-options AND yes I had run "composer dump_autoload" command as well. If option_all doesn't exist anymore then what's solution now?

**Comment by gizburdt** [comment]
It doesn't exist anymore, anywhere in the code. So I'm not sure which version you are using.

**Comment by m-sajjad01** [comment]
This Packagist v5.2.0 is being used . Its mention before the Installation Section. Please look in this [https://github.com/appstract/laravel-options](url)

**Comment by gizburdt** [comment]
The last URL doesn't work

**Comment by gizburdt** [comment]
Just created a fresh install and added this package. I got no errors.. So not sure what's going wrong

**Comment by m-sajjad01** [comment]
@gizburdt The last URL doesn't work. 
Answer: Just copy and paste this URL https://github.com/appstract/laravel-options in browser. 

@gizburdt: Just created a fresh install and added this package. I got no errors.. So not sure what's going wrong
Answer: Yes, you may be right because on fresh installation it will not show any error. Have you installed it on Laravel 8? 
              It throws error when I put a custom user defined function in "vendor/appstract/laravel-options/src/helpers.php"
              This is the function 
               if (! function_exists('option_all')) {
                 /**
                   * Get all options in key => value pair
                   *
                   * @return array
                   */
                   function option_all() {
                        return app('option')->option_all();
                    }
               }

**Comment by gizburdt** [comment]
`app('option')->option_all();` doesn't exist, that's the error you're getting

**Comment by m-sajjad01** [comment]
@gizburdt  Can i create and put my custom function in this helper file --> " vendor/appstract/laravel-options/src/helpers.php" ?

**Comment by gizburdt** [comment]
You can't put custom code in the /vendor folder

**Comment by m-sajjad01** [comment]
OK, Thank you for your response.
