### ISSUE TITLE
Migrate error on MariaDB

### ISSUE THREAD

**Issue by animexxx** [appstract/laravel-options#58]
Hi, 
I have try and it work on local but when i push to live server running MariaDB the migrate error
` SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'' at line 1 (SQL: create table `options` (`id` bigint unsigned not null auto_increment primary key, `key` varchar(191) not null, `value` json not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

I think it because MariaDB not support json type. Please advise. 

Thank for great tool

**Comment by swichers** [comment]
MariaDB supports JSON https://mariadb.com/kb/en/json-data-type/ . If your MariaDB version is from before 2017 you can try to update.
