### ISSUE TITLE
tag 5.5.0 breaks options with empty array [].

### ISSUE THREAD

**Issue by deonthomasgy** [appstract/laravel-options#66]
replicate: 

Option('testing' array());

return Option('testing');

**Comment by deonthomasgy** [comment]
looks like the new --encrypt feature is not tested well with arrays.

**Comment by teuunn** [comment]
Related #65 
Maybe @jornatf has time to look into it. @deonthomasgy if you find a solution PR is welcome. Otherwise I'll try later.

**Comment by jornatf** [comment]
Hi, I'll check it out and get back to you ASAP.

**Comment by gizburdt** [comment]
I reverted the commit for now in 5.6.0. I think the encryption feature is a nice one, but I have a few suggestions:
- Please provide new code with tests
- I don't really get the name `->crypt()` for the method, why not just `->encrypt()`
- I saw the `crypt` method encrypts the value with an update, after it is already set in the database. I think it's cleaner if we could find a way to directly set the encrypted value in the database.

Thanks for the help! :) Hope to see a new PR from you :)
