### ISSUE TITLE
Laravel 11 

### ISSUE THREAD

**Issue by cjonstrup** [appstract/laravel-options#69]
Hi, is this upgraded to support Laravel 11

```  Problem 1
    - Root composer.json requires appstract/laravel-options ^5.7 -> satisfiable by appstract/laravel-options[5.7.0].
    - appstract/laravel-options 5.7.0 requires illuminate/support ^6.0|^7.0|^8.0|^9.0|^10.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.```

**Comment by gizburdt** [comment]
We're open for PR's :)

**Comment by cjonstrup** [comment]
I have made a quick one, removed old php support etc. Upgraded to use github action. I dont know if that the direction you want for the project  and you are free to take what you like.

https://github.com/appstract/laravel-options/compare/master...Lenius:laravel-options:master

Added phpstan and test flow you can see here.
https://github.com/Lenius/laravel-options/actions

**Comment by WoutSpits** [comment]
Any updates on when Laravel 11 will be supported?

**Comment by gizburdt** [comment]
Just tagged 6.0.0 with Laravel 11 support :)
