### ISSUE TITLE
Allow calling exists() via helper function

### ISSUE THREAD

**Issue by djam90** [appstract/laravel-options#8]
It would be nice if we could use the `exists` method via the helper function, as follows:

```
option()->exists("key")
```

This would be better than relying on the alias.

**Comment by teuunn** [comment]
Hi @djam90, thanks for your message. 

You can already [use it](https://github.com/appstract/laravel-options/blob/master/src/helpers.php#L16). Instead of retrieving the value by option('key'), you can call option()->exists('key) which, ofcourse, will return true or false.
